<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IceSync.Common\IceSync.Common.csproj" />
    <ProjectReference Include="..\IceSync.Data.Models\IceSync.Data.Models.csproj" />
    <ProjectReference Include="..\IceSync.Data\IceSync.Data.csproj" />
    <ProjectReference Include="..\IceSync.Infrastructure\IceSync.Infrastructure.csproj" />
    <ProjectReference Include="..\IceSynd.Services.Contracts\IceSynd.Services.Contracts.csproj" />
  </ItemGroup>

</Project>
